{% set name = "pyfastner" %}
{% set version = "1.0.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/PyFastNER-{{ version }}.tar.gz
  sha256: ccb92fa18ec585438aa47d5d6156222fe91d8f7eba2f56121db13243c0e25b66

build:
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - python
    - cython
    - pip
    - setuptools
    - wheel
  run:
    - python
    - quicksectx >=0.3.1

test:
  imports:
    - PyFastNER
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/jianlins/PyFastNER
  dev_url: https://github.com/jianlins/PyFastNER
  doc_url: https://github.com/jianlins/PyFastNER
  summary: A fast implementation of dictionary based named entity recognition.
  description: |
    A fast implementation of dictionary based named entity recognition.
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE

extra:
  recipe-maintainers:
    - skupr-anaconda
