{% set name = "PyFastNER" %}
{% set version = "1.0.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
    sha256: d477fc4f7acbb68f0c828b0bed478206092bb8190997dfda006993db5813b262

    # Github src for TESTS only
    # Upstream github src version 1.0.10 does not exist here, so we take the latest available for test only.
    # TODO: check/fix this once new of right version upstream available
  - url: https://github.com/jianlins/{{ name }}/archive/refs/tags/1.0.9.tar.gz
    sha256: e8e1072c94c4e486a56a5580f5b47756ae2c93e6f9f1581870fdd3cc5bd251b4
    folder: gh_src

  - patches:
      # pypi upstream doesn't have requirements.txt file
      # github upstream doesn't release 1.0.10 version so cannot be used instead
      - patches/0001-fix-missing-upstream-requirements-file.patch

build:
  number: 1
  skip: true  # [py<37]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vv

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
  host:
    - python
    - cython
    - pip
    - setuptools >=61.0.0
    - wheel
    - quicksectx >=0.3.1
  run:
    - python
    - quicksectx >=0.3.1
    - cython

test:
  source_files:
    - gh_src/tests/crule_test.tsv
    - gh_src/tests/test_FastCNER.py
  imports:
    - PyFastNER
  requires:
    - pip
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    - python gh_src/tests/test_FastCNER.py

about:
  home: https://github.com/jianlins/PyFastNER
  summary: A fast implementation of dictionary based named entity recognition.
  description: |
    A fast implementation of dictionary based named entity recognition.
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  dev_url: https://github.com/jianlins/PyFastNER
  doc_url: https://github.com/jianlins/PyFastNER

extra:
  recipe-maintainers:
    - skupr-anaconda