{% set name = "pyfastner" %}
{% set version = "1.0.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/PyFastNER-{{ version }}.tar.gz
  sha256: d477fc4f7acbb68f0c828b0bed478206092bb8190997dfda006993db5813b262

build:
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  number: 0
  skip: true  # [py<37]

requirements:
  host:
    - python
    - cython
    - pip
    - setuptools >=61.0.0
    - wheel
    - quicksectx >=0.3.1
  run:
    - python
    - quicksectx >=0.3.1
    - cython
  build:
    - {{ compiler('c') }}

test:
  imports:
    - PyFastNER
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/jianlins/PyFastNER
  dev_url: https://github.com/jianlins/PyFastNER
  doc_url: https://github.com/jianlins/PyFastNER
  summary: A fast implementation of dictionary based named entity recognition.
  description: |
    A fast implementation of dictionary based named entity recognition.
  license: Apache-2.0
  license_family: Apache
  # the sourse code is missing the license file
  license_url: https://github.com/jianlins/PyFastNER/blob/master/LICENSE

extra:
  recipe-maintainers:
    - skupr-anaconda
  skip-lints:
    - cython_needs_compiler
